[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["cd server && pip install -r requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "cd server && uvicorn app:app --host 0.0.0.0 --port ${PORT:-8000}"
